name: Hello World Docker CI
on:
  push:
    branches: main
    paths: hello-world-docker-action/action.yml
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      
      - name: Hello world action step
        id: Hello
        uses: ./hello-world-docker-action
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
